name: halo-s2
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - rasterio
  - shapely
  - pyproj
  - pandas
  - numpy
  - pyarrow
  - psutil
  - pip
  - pip:
      - planetary-computer
      - pystac-client
      - odc-stac
